repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local
    hooks:
      - id: check-imports
        name: Check Python imports
        entry: python -c "import app.models.synthesis; import app.services.synthesis; print('Imports OK')"
        language: system
        pass_filenames: false
      
      - id: folder-structure-cleanup
        name: Clean up folder structure
        entry: python scripts/cleanup_folder_structure.py --pre-commit
        language: system
        pass_filenames: false
        always_run: true
        stages: [commit]
