# Second Brain Full Application Stack
# Includes the application along with all dependencies
# Run: docker-compose -f docker-compose.yml -f docker-compose.app.yml up -d

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: secondbrain-app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Database
      DATABASE_URL: postgresql+asyncpg://secondbrain:changeme@postgres:5432/secondbrain
      
      # Redis
      REDIS_URL: redis://redis:6379/0
      
      # Application settings
      APP_ENV: development
      LOG_LEVEL: info
      SECRET_KEY: ${SECRET_KEY:-development-secret-key-change-in-production}
      
      # CORS settings
      CORS_ORIGINS: '["http://localhost:3000","http://localhost:8000","http://localhost:8001"]'
      
      # File handling
      TEMP_DIR: /app/temp
      MAX_UPLOAD_SIZE: 104857600  # 100MB
      
      # Feature flags
      USE_MOCK_DATABASE: "false"
      ENABLE_TELEMETRY: "false"
      
      # OpenAI (optional)
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      
    ports:
      - "8000:8000"
    volumes:
      # Code mounting for development (comment out for production)
      - ./app:/app/app:ro
      - ./main.py:/app/main.py:ro
      
      # Data persistence
      - app_data:/app/data
      - app_logs:/app/logs
      - app_temp:/app/temp
      
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  app_data:
    name: secondbrain_app_data
  app_logs:
    name: secondbrain_app_logs
  app_temp:
    name: secondbrain_app_temp