services:
  second-brain:
    build: .
    container_name: second_brain_production
    image: ${DOCKER_REGISTRY:-localhost}/second-brain:production-latest
    ports:
      - "8000:8000"
    depends_on:
      - qdrant-production
    networks:
      - app-net-production
    restart: unless-stopped
    environment:
      APP_ENV: production
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      API_TOKENS: ${PRODUCTION_API_TOKENS}
      OPENAI_EMBEDDING_MODEL: text-embedding-3-small
      LOG_PATH: logs/processor-production.log
      LOG_LEVEL: WARNING  # Less verbose in production
      QDRANT_HOST: qdrant-production
      QDRANT_PORT: 6333
      QDRANT_COLLECTION_NAME: memories-production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  qdrant-production:
    image: qdrant/qdrant:latest
    container_name: qdrant_production
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data_production:/qdrant/storage
    networks:
      - app-net-production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

networks:
  app-net-production:
    driver: bridge 