# Deployment Configuration for llm_output_processor

## docker-compose.yml
#  - Mounts the local `./app` directory into the container at `/app/app` to preserve the `app.` import namespace.
#  - Includes a `qdrant` service for vector storage.
#  - Logging and restart policies configured.

services:
  llm-output-processor:
    build: .
    container_name: llm_output_processor
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - qdrant
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-net:
    driver: bridge
