# Second Brain - Docker-First Development Environment
# Complete containerized development stack
# Zero host dependencies beyond Docker

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: secondbrain-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://secondbrain:changeme@postgres:5432/secondbrain
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
      - TEMP_DIR=/app/temp
    volumes:
      - .:/app:rw
      - /app/.venv  # Exclude .venv from mount
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
  postgres:
    image: pgvector/pgvector:pg16
    container_name: secondbrain-postgres
    environment:
      POSTGRES_USER: secondbrain
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: secondbrain
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U secondbrain"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: secondbrain-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: secondbrain-adminer
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data: