# Claude Code Configuration for Second Brain Project
# Version 2.0 - Security & Performance Optimized

version: "2.0"
schema_version: "2024-01-15"

# Project metadata
project:
  name: "second-brain"
  type: "knowledge-management"
  security_level: "standard"
  compliance: ["SOC2-pending"]

# Smart activation strategy - not all agents at once
activation_strategy: "smart"

# Agent groups with security-based tool restrictions
agent_groups:
  # Always active - minimal tools
  essential:
    agents: 
      - knowledge-synthesizer
      - note-processor
      - context-aware-orchestrator
    always_active: true
    max_concurrent: 2
    tools_allowed: [Read, Write, Grep, Task]
    
  # On-demand analysis - read-only
  analysis:
    agents:
      - performance-analyzer
      - code-quality-analyzer
      - architecture-analyzer
    activation_trigger: "explicit"
    max_concurrent: 1
    tools_allowed: [Read, Grep, Glob, LS]
    
  # Documentation - no web access
  documentation:
    agents:
      - api-documentation-agent
      - architecture-documentation-agent
      - adr-generator
    activation_trigger: "file_change"
    file_patterns: ["*.py", "*.md", "*.yml"]
    max_concurrent: 1
    tools_allowed: [Read, Write, Edit, MultiEdit]
    
  # Research - full access but limited
  research:
    agents:
      - research-orchestrator
      - deep-researcher
    activation_trigger: "explicit"
    max_concurrent: 1
    tools_allowed: [Read, Write, Grep, WebSearch, WebFetch, Task]
    rate_limit: "10/hour"
    
  # Security - special permissions
  security:
    agents:
      - security-vulnerability-scanner
      - compliance-checker
    activation_trigger: "scheduled"
    schedule: "0 2 * * *"  # 2 AM daily
    max_concurrent: 1
    tools_allowed: [Read, Grep, WebSearch]
    requires_approval: false
    
  # Maintenance - scheduled only
  maintenance:
    agents:
      - technical-debt-tracker
      - legacy-code-analyzer
      - dependency-manager
    activation_trigger: "scheduled"
    schedule: "0 0 * * 0"  # Weekly Sunday midnight
    max_concurrent: 1
    tools_allowed: [Read, Grep, Write]

# Context files with access controls
context_files:
  read_only:
    - path: "CLAUDE.md"
      cache_ttl_seconds: 3600
    - path: "README.md"
      cache_ttl_seconds: 86400
      
  read_write:
    - path: "TODO.md"
      cache_ttl_seconds: 300
      writers: ["context-aware-orchestrator", "technical-debt-tracker"]
    - path: "DEVELOPMENT_CONTEXT.md"
      cache_ttl_seconds: 60
      writers: ["context-aware-orchestrator"]

# Security configuration
security:
  # Paths that agents cannot access
  restricted_paths:
    - ".env*"
    - ".git/"
    - "*.key"
    - "*.pem"
    - "secrets/"
    - "credentials/"
    - "__pycache__/"
    - "node_modules/"
    - ".venv/"
    
  # File size limits
  file_limits:
    max_read_size_mb: 10
    max_write_size_mb: 5
    max_files_per_operation: 20
    
  # Audit configuration
  audit:
    enabled: true
    log_file: ".claude/audit.log"
    retain_days: 30
    log_level: "INFO"
    
  # Path validation
  path_validation:
    require_absolute_paths: false
    restrict_to_project_root: true
    follow_symlinks: false

# Performance limits
performance:
  # Global limits
  global:
    max_concurrent_agents: 5
    max_tokens_per_minute: 100000
    max_file_operations_per_minute: 100
    
  # Per-agent limits
  per_agent:
    max_tokens_per_invocation: 4000
    max_execution_time_seconds: 30
    max_memory_mb: 512
    
  # Circuit breaker
  circuit_breaker:
    enabled: true
    failure_threshold: 3
    timeout_seconds: 60
    half_open_requests: 1

# Caching configuration
cache:
  # Context file caching
  context_files:
    enabled: true
    strategy: "lru"
    max_size_mb: 50
    
  # Agent result caching
  agent_results:
    enabled: true
    strategy: "ttl"
    default_ttl_seconds: 1800
    max_entries: 1000
    
  # Tool result caching
  tool_results:
    enabled: true
    cache_grep: true
    cache_glob: true
    ttl_seconds: 300

# Monitoring and observability
monitoring:
  # Metrics collection
  metrics:
    enabled: true
    export_interval_seconds: 60
    providers: ["prometheus", "file"]
    
  # Performance tracking
  performance_tracking:
    track_token_usage: true
    track_execution_time: true
    track_error_rates: true
    track_cache_hits: true
    
  # Alerting thresholds
  alerts:
    token_usage_percent: 80
    error_rate_percent: 5
    avg_execution_time_seconds: 10

# Agent behavior configuration
agent_config:
  # Lifecycle hooks
  lifecycle:
    auto_cleanup: true
    save_state_on_error: true
    retry_on_failure: false
    
  # Communication
  communication:
    use_structured_output: true
    validate_schemas: true
    compress_large_payloads: true
    
  # Learning and adaptation
  adaptation:
    track_usage_patterns: true
    optimize_frequent_paths: true
    suggest_new_patterns: false

# Activation rules with security focus
activation_rules:
  - name: "Python code analysis"
    trigger: "file_change"
    pattern: "**/*.py"
    exclude: ["**/test_*.py", "**/__pycache__/**"]
    agents: ["code-quality-analyzer"]
    max_file_size_kb: 500
    
  - name: "Documentation update"
    trigger: "file_change"
    pattern: "**/*.md"
    exclude: ["**/node_modules/**", "**/vendor/**"]
    agents: ["note-processor"]
    debounce_seconds: 5
    
  - name: "Architecture change"
    trigger: "file_change"
    pattern: "src/core/**/*.py"
    agents: ["architecture-analyzer", "adr-generator"]
    requires_confirmation: true
    
  - name: "API modification"
    trigger: "file_change"
    pattern: "src/api/**/*.py"
    agents: ["api-documentation-agent"]
    auto_update_docs: true

# Rollback configuration
rollback:
  enabled: true
  max_versions: 5
  auto_rollback_on_error: false
  checkpoint_interval_minutes: 30

# Development mode overrides
development:
  relaxed_security: false
  verbose_logging: true
  disable_rate_limits: false
  allow_dangerous_operations: false

# Feature flags
features:
  agent_marketplace: false
  custom_mcp_servers: false
  ai_agent_optimization: false
  distributed_execution: false

# Versioning and compatibility
compatibility:
  min_claude_version: "1.0.60"
  max_claude_version: "2.0.0"
  deprecation_warnings: true
  
# Metadata
metadata:
  created_by: "PhD Computer Scientist - Anthropic Engineering"
  last_updated: "2025-07-31"
  review_frequency: "monthly"
  next_review: "2025-08-31"