# Claude Code Configuration for Second Brain Project

# Auto-activate agents when working in this project
auto_activate_agents:
  # System Agents
  - startup-update-checker
  
  # Research & Knowledge Management Agents
  - knowledge-synthesizer
  - research-orchestrator
  - note-processor
  - deep-researcher
  
  # Analysis Agents
  - performance-analyzer
  - code-quality-analyzer
  - architecture-analyzer
  
  # Documentation Agents
  - api-documentation-agent
  - architecture-documentation-agent
  - adr-generator
  
  # Maintenance Agents
  - technical-debt-tracker
  - legacy-code-analyzer
  - dependency-manager
  
  # Security & Compliance Agents
  - security-vulnerability-scanner
  - compliance-checker
  
  # Quality & Testing Agents
  - test-generator
  - code-review-agent
  - performance-optimizer
  
  # Operations Agents
  - incident-response-agent
  - postmortem-generator
  - devops-automation-agent
  
  # Collaboration Agents
  - knowledge-sharing-agent
  - expertise-mapper
  - team-sync-agent
  
  # Integration & Orchestration Agents
  - mcp-integration-agent
  - ci-cd-pipeline-agent
  - tool-orchestrator
  
  # Context-Aware Agents
  - context-aware-orchestrator
  - context-aware-debt-tracker

# Context files for agents to automatically read
context_files:
  - TODO.md
  - CLAUDE.md
  - DEVELOPMENT_CONTEXT.md

# Agent behavior configuration
agent_config:
  auto_read_context: true
  preserve_session_history: true
  update_context_on_completion: true
  
  # Performance settings
  max_concurrent_agents: 10
  agent_timeout_seconds: 300
  
  # Token usage settings
  warn_on_high_token_usage: true
  token_usage_multiplier_threshold: 10
  
  # Logging and monitoring
  log_agent_activity: true
  track_agent_metrics: true
  
# Project-specific agent configurations
project_config:
  second_brain:
    primary_agents:
      - knowledge-synthesizer
      - research-orchestrator
      - note-processor
    
    code_analysis_agents:
      - code-quality-analyzer
      - architecture-analyzer
      - technical-debt-tracker
    
    documentation_agents:
      - architecture-documentation-agent
      - adr-generator
      
# Agent activation rules
activation_rules:
  - trigger: "file_change"
    pattern: "*.py"
    agents: ["code-quality-analyzer", "test-generator"]
    
  - trigger: "file_change"
    pattern: "*.md"
    agents: ["note-processor", "knowledge-synthesizer"]
    
  - trigger: "architecture_change"
    pattern: "src/core/**"
    agents: ["architecture-analyzer", "adr-generator"]
    
  - trigger: "api_change"
    pattern: "src/api/**"
    agents: ["api-documentation-agent"]
    
  - trigger: "security_scan"
    schedule: "daily"
    agents: ["security-vulnerability-scanner", "compliance-checker"]