name: CD

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Log deployment info
      run: |
        echo "🚀 Deployment triggered"
        echo "Branch/Tag: ${{ github.ref }}"
        echo "Commit: ${{ github.sha }}"
        echo "Time: $(date)"
    
    - name: Build Docker image
      run: |
        docker build -t second-brain:${{ github.sha }} .
        echo "✅ Docker image built successfully"
    
    - name: Create deployment artifact
      run: |
        # Create a simple deployment info file
        cat > deployment-info.json << EOF
        {
          "version": "${{ github.ref }}",
          "commit": "${{ github.sha }}",
          "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
          "image": "second-brain:${{ github.sha }}"
        }
        EOF
        
        echo "✅ Deployment artifact created"
        cat deployment-info.json
    
    - name: Upload deployment artifact
      uses: actions/upload-artifact@v3
      with:
        name: deployment-info
        path: deployment-info.json
        retention-days: 30
    
    # Add your actual deployment steps here when ready
    # For now, this just builds and validates the image