name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: test
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov ruff

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Auto-fix lint issues (ruff)
        run: |
          ruff check . --fix || echo "Lint auto-fixed"

      - name: Run Linting (ruff)
        run: |
          ruff check .

      - name: Debug PYTHONPATH
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          ls -la /home/runner/work/second-brain/second-brain/app

      - name: Run Tests with Coverage
        run: |
          export PYTHONPATH=./app
          pytest --cov=app tests/

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/
