name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create Pages directory
        run: |
          mkdir -p _site
          
          # Copy main index.html
          cp index.html _site/
          
          # Copy all static files
          cp -r static/* _site/
          
          # Create a simple 404 page
          cat > _site/404.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Second Brain - Page Not Found</title>
              <style>
                  body { 
                      font-family: -apple-system, BlinkMacSystemFont, sans-serif; 
                      text-align: center; 
                      padding: 50px;
                      background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                      color: white;
                      margin: 0;
                      height: 100vh;
                      display: flex;
                      align-items: center;
                      justify-content: center;
                      flex-direction: column;
                  }
                  .content {
                      background: rgba(255,255,255,0.1);
                      padding: 40px;
                      border-radius: 20px;
                      backdrop-filter: blur(10px);
                  }
                  a {
                      color: white;
                      text-decoration: none;
                      background: rgba(255,255,255,0.2);
                      padding: 10px 20px;
                      border-radius: 5px;
                      display: inline-block;
                      margin-top: 20px;
                  }
              </style>
          </head>
          <body>
              <div class="content">
                  <h1>🧠 Second Brain</h1>
                  <h2>Page Not Found</h2>
                  <p>The page you're looking for doesn't exist.</p>
                  <a href="/">Return to Home</a>
              </div>
          </body>
          </html>
          EOF
          
          # Create a sitemap
          cat > _site/sitemap.xml << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
              <url>
                  <loc>https://raold.github.io/second-brain/</loc>
                  <lastmod>2025-01-22</lastmod>
                  <priority>1.0</priority>
              </url>
              <url>
                  <loc>https://raold.github.io/second-brain/knowledge-graph.html</loc>
                  <lastmod>2025-01-22</lastmod>
                  <priority>0.8</priority>
              </url>
              <url>
                  <loc>https://raold.github.io/second-brain/tufte_dashboard.html</loc>
                  <lastmod>2025-01-22</lastmod>
                  <priority>0.8</priority>
              </url>
              <url>
                  <loc>https://raold.github.io/second-brain/dashboard.html</loc>
                  <lastmod>2025-01-22</lastmod>
                  <priority>0.7</priority>
              </url>
          </urlset>
          EOF
          
          echo "✅ GitHub Pages site prepared"
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4