name: Test Quality Review

on:
  schedule:
    # Run weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:
    # Allow manual trigger

jobs:
  test-quality-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-cov pytest-html pytest-json-report
    
    - name: Run comprehensive test analysis
      run: |
        # Run tests with detailed reporting
        pytest \
          --cov=app \
          --cov-report=html \
          --cov-report=xml \
          --cov-report=json \
          --html=test-report.html \
          --json-report \
          --json-report-file=test-results.json \
          --durations=20 \
          --tb=short
    
    - name: Generate test quality report
      run: |
        python scripts/test-quality-analyzer.py
    
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        name: test-quality-reports
        path: |
          htmlcov/
          test-report.html
          test-results.json
          coverage.xml
          test-quality-report.md
    
    - name: Comment PR if coverage drops
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const path = 'test-quality-report.md';
          if (fs.existsSync(path)) {
            const report = fs.readFileSync(path, 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: report
            });
          }