name: Test Synthesis Features

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/models/synthesis/**'
      - 'app/services/synthesis/**'
      - 'app/routes/synthesis_routes.py'
      - 'tests/**/synthesis/**'

jobs:
  test-synthesis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-asyncio pytest-cov
      
      - name: Run synthesis tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          USE_MOCK_DATABASE: true
        run: |
          # Test models
          echo "Testing synthesis models..."
          python -m pytest tests/unit/synthesis/test_report_models.py -v
          python -m pytest tests/unit/synthesis/test_repetition_models.py -v
          python -m pytest tests/unit/synthesis/test_websocket_models.py -v
          
          # Test services
          echo "Testing synthesis services..."
          python -m pytest tests/unit/synthesis/test_report_generator.py -v
          python -m pytest tests/unit/synthesis/test_repetition_scheduler.py -v
          python -m pytest tests/unit/synthesis/test_websocket_service.py -v
          
          # Test integration
          echo "Testing synthesis integration..."
          python -m pytest tests/integration/synthesis/test_synthesis_integration.py -v
      
      - name: Check imports
        run: |
          echo "Checking synthesis imports..."
          python -c "from app.models.synthesis import *; print('Models OK')"
          python -c "from app.services.synthesis import *; print('Services OK')"
          python -c "from app.routes.synthesis_routes import router; print('Routes OK')"