name: Test Synthesis Features

on:
  workflow_dispatch:
  push:
    paths:
      - 'app/models/synthesis/**'
      - 'app/services/synthesis/**'
      - 'app/routes/synthesis_routes.py'
      - 'tests/**/synthesis/**'

jobs:
  test-synthesis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies  
        run: |
          python -m pip install --upgrade pip
          # Install core dependencies first to avoid conflicts
          pip install fastapi==0.109.0 pydantic==2.5.3 uvicorn[standard]==0.27.0
          pip install sqlalchemy==2.0.25 asyncpg==0.29.0 httpx==0.26.0
          pip install redis==5.0.1 python-dotenv==1.0.0 openai==1.3.8
          pip install psutil==5.9.0 structlog==25.4.0 numpy==1.26.3
          pip install pytest==7.4.4 pytest-asyncio==0.23.3 pytest-cov==4.1.0
          pip install scikit-learn==1.3.2 pandas==2.0.3 networkx==3.2.1
          pip install jinja2==3.1.2 python-multipart==0.0.6
      
      - name: Run synthesis tests
        env:
          PYTHONPATH: ${{ github.workspace }}
          USE_MOCK_DATABASE: true
        run: |
          # Test models
          echo "Testing synthesis models..."
          python -m pytest tests/unit/synthesis/test_report_models.py -v
          python -m pytest tests/unit/synthesis/test_repetition_models.py -v
          python -m pytest tests/unit/synthesis/test_websocket_models.py -v
          
          # Test services
          echo "Testing synthesis services..."
          python -m pytest tests/unit/synthesis/test_report_generator.py -v
          python -m pytest tests/unit/synthesis/test_repetition_scheduler.py -v
          python -m pytest tests/unit/synthesis/test_websocket_service.py -v
          
          # Test integration
          echo "Testing synthesis integration..."
          python -m pytest tests/integration/synthesis/test_synthesis_integration.py -v
      
      - name: Check imports
        run: |
          echo "Checking synthesis imports..."
          python -c "from app.models.synthesis import *; print('Models OK')"
          python -c "from app.services.synthesis import *; print('Services OK')"
          python -c "from app.routes.synthesis_routes import router; print('Routes OK')"