name: CI Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements-ci.txt
    
    - name: Run unit tests
      env:
        TESTING: true
        USE_MOCK_DATABASE: true
        ENVIRONMENT: test
      run: |
        python -m pytest tests/unit -v --tb=short