name: Test v3.0.0

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PYTHON_VERSION: '3.11'
  USE_MOCK_DATABASE: 'true'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r config/requirements-ci.txt
    
    - name: Run validation tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python scripts/test_runner.py --validation
    
    - name: Run unit tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: |
        python scripts/test_runner.py --unit